### ISSUE TITLE
在终端里输出了，qemu没有输出

### ISSUE THREAD

**Issue by Tziheng** [Alpha-Girl/OS2021_labs#21]
![-45d512a38a0ec51.png](https://user-images.githubusercontent.com/67832547/114259980-8cefbb00-9a04-11eb-8df0-cb65efe9c2e7.png)
这是为什么

**Comment by Alpha-Girl** [comment]
qemu里输出了个n，可能说换行/滚屏等操作时出了问题？

**Comment by ZhaoZuohong** [comment]
你写得不对呗

**Comment by Tziheng** [comment]
是这样的，只输出了最后一个shutdown的n，忘了偏移地址了
