### ISSUE TITLE
/*格式：XXX_ITEM_NAME=value*/ XXX的意思

### ISSUE THREAD

**Issue by Georgefwt** [Alpha-Girl/OS2021_labs#4]
/*格式：XXX_ITEM_NAME=value*/ 这个XXX是什么？
还有这里.section “.xxx”
 “.globl XXLabel” 
XX这里表示自己随意命名吗？

**Comment by Alpha-Girl** [comment]
/*此处，按照multiboot协议要求定义必要的参数*/
/*格式：XXX_ITEM_NAME=value*/
/*value可以是十六进制的（0x开头）、十进制的等等*/
/*为便于阅读，可以适当增加一些注释和空行*/

这个的XXX_ITEM_NAME就是 某个参数名的意思。举个例子：
```
/*MULTIBOOT_HEADER_MAGIC=0x1BADB002*/
#define      MULTIBOOT_HEADER_MAGIC                  0x1BADB002
```

XX这里表示自己随意命名，不过命名要尽量符合代码规范。
