### ISSUE TITLE
start标识符后面的代码的作用

### ISSUE THREAD

**Issue by Georgefwt** [Alpha-Girl/OS2021_labs#8]
start标识符后面的代码的作用是什么？可以为空吗？
另外，如何连续的写显存？
```
movl $0x2f4b2f4e, 0xB8000
movl $0x2f4b2f4e, 0xB8004
```
会报错`qemu-system-i386: Error loading uncompressed kernel without PVH ELF Note`
只有第一句时能正常运行。怎么解决？

**Comment by katarXu** [comment]
可以为空

比如这样：
```
        .globl  start, _start
start:
_start:
        hlt
```
可以连续写缓存，这样写没有问题

**Comment by ZhaoZuohong** [comment]
> start标识符后面的代码的作用是什么？可以为空吗？
> 另外，如何连续的写显存？
> 
> ```
> movl $0x2f4b2f4e, 0xB8000
> movl $0x2f4b2f4e, 0xB8004
> ```
> 
> 会报错`qemu-system-i386: Error loading uncompressed kernel without PVH ELF Note`
> 只有第一句时能正常运行。怎么解决？

你是怎么编译链接的

**Comment by Alpha-Girl** [comment]
用`lsb_release -a`看一下Ubuntu的版本，有两位使用Ubuntu20.04LTS的同学都出现了这个问题，换到Ubuntu18.04LTS就能正常运行。
目前还没把握到问题的具体原因，因为lab1的代码量不是很大，建议换到Ubuntu18.04LTS上试试。

**Comment by Georgefwt** [comment]
> 用`lsb_release -a`看一下Ubuntu的版本，有两位使用Ubuntu20.04LTS的同学都出现了这个问题，换到Ubuntu18.04LTS就能正常运行。
> 目前还没把握到问题的具体原因，因为lab1的代码量不是很大，建议换到Ubuntu18.04LTS上试试。

好吧，我是20.04LTS。。。

**Comment by Georgefwt** [comment]
> > start标识符后面的代码的作用是什么？可以为空吗？
> > 另外，如何连续的写显存？
> > ```
> > movl $0x2f4b2f4e, 0xB8000
> > movl $0x2f4b2f4e, 0xB8004
> > ```
> > 
> > 
> > 会报错`qemu-system-i386: Error loading uncompressed kernel without PVH ELF Note`
> > 只有第一句时能正常运行。怎么解决？
> 
> 你是怎么编译链接的

`qemu-system-i386 -kernel multibootHeader.bin -serial stdio`
换发行版有点麻烦，有20.04lts的解决方案吗？

**Comment by ZhaoZuohong** [comment]
> > > start标识符后面的代码的作用是什么？可以为空吗？
> > > 另外，如何连续的写显存？
> > > ```
> > > movl $0x2f4b2f4e, 0xB8000
> > > movl $0x2f4b2f4e, 0xB8004
> > > ```
> > > 
> > > 
> > > 会报错`qemu-system-i386: Error loading uncompressed kernel without PVH ELF Note`
> > > 只有第一句时能正常运行。怎么解决？
> > 
> > 
> > 你是怎么编译链接的
> 
> `qemu-system-i386 -kernel multibootHeader.bin -serial stdio`
> 换发行版有点麻烦，有20.04lts的解决方案吗？

你是怎么编译链接的

**Comment by Georgefwt** [comment]
> > > > start标识符后面的代码的作用是什么？可以为空吗？
> > > > 另外，如何连续的写显存？
> > > > ```
> > > > movl $0x2f4b2f4e, 0xB8000
> > > > movl $0x2f4b2f4e, 0xB8004
> > > > ```
> > > > 
> > > > 
> > > > 会报错`qemu-system-i386: Error loading uncompressed kernel without PVH ELF Note`
> > > > 只有第一句时能正常运行。怎么解决？
> > > 
> > > 
> > > 你是怎么编译链接的
> > 
> > 
> > `qemu-system-i386 -kernel multibootHeader.bin -serial stdio`
> > 换发行版有点麻烦，有20.04lts的解决方案吗？
> 
> 你是怎么编译链接的

make
makefile 直接抄ppt的

**Comment by ZhaoZuohong** [comment]
确认是QEMU版本的问题

**Comment by ZhaoZuohong** [comment]
> > > > > start标识符后面的代码的作用是什么？可以为空吗？
> > > > > 另外，如何连续的写显存？
> > > > > ```
> > > > > movl $0x2f4b2f4e, 0xB8000
> > > > > movl $0x2f4b2f4e, 0xB8004
> > > > > ```
> > > > > 
> > > > > 
> > > > > 会报错`qemu-system-i386: Error loading uncompressed kernel without PVH ELF Note`
> > > > > 只有第一句时能正常运行。怎么解决？
> > > > 
> > > > 
> > > > 你是怎么编译链接的
> > > 
> > > 
> > > `qemu-system-i386 -kernel multibootHeader.bin -serial stdio`
> > > 换发行版有点麻烦，有20.04lts的解决方案吗？
> > 
> > 
> > 你是怎么编译链接的
> 
> make
> makefile 直接抄ppt的

问题确认，是ld和S文件里面代码段名称不一致的原因。
