### ISSUE TITLE
Makefile文件怎么运行

### ISSUE THREAD

**Issue by Tziheng** [Alpha-Girl/OS2021_labs#9]
Makefile不知道如何运行

**Comment by ZhaoZuohong** [comment]
进入`Makefile`文件所在文件夹，运行`make` @Tziheng

**Comment by Tziheng** [comment]
make之后报错，缺失分隔符，停止。
![7f18b5303c51a921](https://user-images.githubusercontent.com/67832547/111897584-b21f8800-8a5b-11eb-8c94-eaa18ee67fe4.jpg)

**Comment by dingfen** [comment]
Makefile 里的内容需要严格按照ppt的方式书写  不能用空格缩进 用tab

**Comment by Tziheng** [comment]
> Makefile 里的内容需要严格按照ppt的方式书写  不能用空格缩进 用tab

确实是使用tab缩进

**Comment by Tziheng** [comment]
![-51d394e9d55f952f.png](https://user-images.githubusercontent.com/67832547/111897664-47228100-8a5c-11eb-93ca-58301f05b3dd.png)
应该和PPT上一样

**Comment by ZhaoZuohong** [comment]
粘代码 @Tziheng

**Comment by Tziheng** [comment]
> 粘代码 @Tziheng 

我大概明白了，pluma会自动把tab变成4个空格，我在记事本上重新写了一个发了上去，能运行了，不过还有报错

**Comment by Tziheng** [comment]
报错如图所示
![447379ad5b7b48c1.jpg](https://user-images.githubusercontent.com/67832547/111897987-088dc600-8a5e-11eb-9a90-31e8fbd86ccf.jpg)

**Comment by ZhaoZuohong** [comment]
康康ld文件

> 报错如图所示
> ![447379ad5b7b48c1.jpg](https://user-images.githubusercontent.com/67832547/111897987-088dc600-8a5e-11eb-9a90-31e8fbd86ccf.jpg)

**Comment by Tziheng** [comment]
好，ld文件我重新在电脑上写了一遍再发送到vlab，已经没有保错了
